satya164/react-native-tab-view

example/src/ListViewExample.js
example/src/TabViewExample.js
src/TabViewAnimated.js
src/TabViewPanResponder.js
src/TabViewPropTypes.js
src/TabViewTransitioner.js
src/TabViewTypeDefinitions.js

Improve horizontal swipe detection

---

README.md
src/TabBar.js
src/TabBarTop.js
src/TabViewAnimated.js
src/TabViewPage.js
src/TabViewTransitioner.js

I removed `shouldComponentUpdate` from all components other than `TabViewAnimated` and `TabViewTransitioner` since they are rendered by `TabViewTransitioner`, hence the extra `shouldComponentUpdate` is not necessary.
cc @skevy @knowbody

feat: add a shouldOptimizeUpdates prop to customize shouldComponentUpdate behaviour

---

src/TabViewPanResponder.js

eslint spits out:
```
/home/wli/projects/react-native-tab-view/src/TabViewPanResponder.js
3:10  error  'Animated' is defined but never used  no-unused-vars
```

cleanup: remove unused Animated import

---

src/TabViewTransitioner.js

Attempting to add flow to my project, and encountered this:
```
node_modules/react-native-tab-view/src/TabViewTransitioner.js:94
94:     this._transitionTo(this.props.navigationState.index);
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `_transitionTo`
94:     this._transitionTo(this.props.navigationState.index);
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ undefined (too few arguments, expected default/rest parameters). This type is incompatible with
145:   _transitionTo = (toValue: number, callback: Function) => {
^^^^^^^^ function type
```

fix: optional callback for _transitionTo

---

src/TabViewTransitioner.js

I just upgraded my app to React Native 0.34 and I have a react-native-maps `MapView` in one of my tabs.
I noticed that the map was continuously rendering and pinned it down to the `TabViewTransitioner#_handleLayout()`. It calls `setState()` even if the width and height haven't changed so this patch stops that.
There was actually a recent RN commit for `NavigationTransitioner` that does the same thing here: https://github.com/facebook/react-native/commit/dadfe40f55f0fc21e833e36ac2ad67ec4160af25

Only update layout state if it changed

---

src/TabBar.js

This PR simply replaces the root container of the `TabBar` component from `View` to `Animated.View`. 
This way, properties like `backgroundColor` can be dynamically animated based on the active tab.
I don't think there are any side effects to doing this, but let me know if I'm missing something. 
Cheers!

Use Animated.View for TabBar root container

---

src/TabViewPanResponder.js

After playing with this library on a few different devices (iOS and Android) it became apparent that the capture point for horizontal scrolling is too sensitive.
This is even more noticeable on phones like the Galaxy S7 and S7 Edge where it became almost impossible to tap on buttons as the swipe capture would take over onTapStart.
This pull adds a `-20 => 20`pt deadzone before capture begins - in other words, when dragging the motion needs to traverse more than 20pt before the PanResponder becomes responder. Might want to make this configurable via component props - although probably not necessary.
For normal swiping the deadzone isn't noticeable while allowing for more natural UI interaction.

Added a 'deadzone' before PanResponder capture.

---

src/TabBar.js

Hi, guys!
This PR brings ability to use accessibilityLabel on Android while E2E-testing

Add "accessible" and "accessibilityLabel" props into <TouchableItem />

---

src/TabBar.js

Hi @satya164, it's me, again. I want to discuss one more time and suggest solution for two attributes: `accessible` and `accessibilityLabel`.
May be you know, that all `Touchable…` components with attribute `accessible="true"` make content inside inaccessible. I want to fix this behaviour and let the user define this attribute.
Also for `accessibilityLabel` common case — set both `testID` and `accessibilityLabel` only one value.
In my team we are using the next helper for `accessibilityLabel`s and `testID`s:
```js
import { Platform } from 'react-native'
export default function testID(id) {
return Platform.OS === 'android' ?
{ accessible: true, accessibilityLabel: id } :
{ testID: id }
}
```
And how we use it:
```js
<TouchableHighlight
style={[styles.button, this.props.isLoading && …
```

Update accessible and accessibilityLabel fields

---

package.json

I noticed this dependency was added to the dependencies of my app after upgrading to the latest version. However, it's only needed during development, so it can be moved to `devDependencies`.

chore: move eslint-plugin-prettier to devDependencies

---

example/src/BottomBarIconTextExample.js
example/src/CoverflowExample.js
example/src/NoAnimationExample.js
example/src/ScrollViewsExample.js
example/src/TopBarIconExample.js
example/src/TopBarTextExample.js
src/TabViewAnimated.js
src/TouchableItem.js

Follow-up to #230: for compatibility with both RN 0.44.0 as well as earlier versions, we decided there to just omit all of these PropTypes.
Besides just removing these PropTypes, here is an alternate approach we can take here to preserve compatibility across RN versions:
```javascript
import {
View,
ViewPropTypes,
} from 'react-native';
...
tabStyle: ViewPropTypes ? ViewPropTypes.style : View.propTypes.style,
```
The destructuring import assigns undefined if the requested module does not exist in the specified file. Meanwhile, Flow is crippled on 0.43.4 by the problem [this commit fixed](https://github.com/facebook/react-native/commit/c7387fefc85fd15dceadfa291857099ed3e848b8), so it doesn't complain about the misnamed import. I've tested this on RN 0.43.4, RN 0.44.0, and master.

Remove all references to View.propTypes

---

src/TabViewPagerScroll.js

the scroll no work because of `e.nativeEvent.contentOffset.x ` and `this._nextOffset` are not  exactly equal when touch  tab of some phones like XiaoMi 5Plus.
```
_handleScroll e.nativeEvent.contentOffset.x 1178.1817626953125 this._nextOffset 1178.1817932128906
```

Fix scroll failed when touch  tab of some phones like XiaoMi 5Plus.

---

README.md
src/TabViewPagerPan.js

There is a bug in React Native that makes gestures to conflict when a PanResponder is put inside of a ScrollView. The workaround for this is to listen to PanResponder start and finish events and toggle ScrollView's `scrollEnabled` accordingly.
Fixes #289

Add onSwipeStart and onSwipeEnd props to TabViewPagerPan

---

src/TabViewPagerPan.js

For some reason whenever my Expo app throws an error this small error will get captured instead.
For example if I don't import `Text` from `react-native` but then try and use `Text`. The red screen will show `undefined is not an object (evaluating 'this._resetListener.remove')` somewhere. My guess is a try catch somewhere is causing this misdirection. Added a simple safety to this line allows me to properly see my errors.
BTW Love the library so far, thanks for all your work!

Add safety check to _resetListener

---

src/TabBar.js

This adds `pointerEvents={'none'}` to the `View` inside the `TouchableItem` to improve the ripple effect.

Update TabBar component to improve ripple effect

---

.eslintrc
.flowconfig
.gitignore
README.md
__tests__/TabViewAnimated.test.js
__tests__/TabViewPagerAndroid.test.js
__tests__/TabViewPagerPan.test.js
__tests__/TabViewPagerScroll.test.js
example/package.json
example/rn-cli.config.js
example/src/App.js
example/src/BottomBarIconTextExample.js
example/src/CoverflowExample.js
example/src/NativeDriverExample.js
example/src/NoAnimationExample.js
example/src/ScrollViewsExample.js
example/src/SimplePage.js
example/src/TopBarTextExample.js
example/yarn.lock
package.json
src/TabBar.js
src/TabViewAnimated.js
src/TabViewPagerAndroid.js
src/TabViewPagerExperimental.js
src/TabViewPagerPan.js
src/TabViewPagerScroll.js
src/TabViewPropTypes.js
src/TabViewTypeDefinitions.js
src/index.js
yarn.lock

This adds a pager component based on [react-native-gesture-handler](kmagiera/react-native-gesture-handler), exposed as `TabViewPagerExperimental`. It'll allow you to use native animations and gestures to achieve much better performance.
This is a breaking change because the now pagers receive two new animated values (`panX` and `offsetX`) to control the `position` instead of a single `position` prop, and the `position` prop in no longer an `Animated.Value`. While you can still interpolate and do other operations on it, you cannot add listeners anymore or call `.setValue` on it. If you need to listen to updates, use the `position` event.
The other pagers have gone through a significant refactor to be able to co-exist with `TabViewPagerExperimental`. While the API stays the same, this can …

BREAKING: add support for react-native-gesture-handler

---

src/TabViewPagerAndroid.js

Similar to issue #365 , when react-native throws an error, this error is thrown instead as `undefined is not an object (evaluating 'this._resetListener.remove')`. 
This makes debugging the original problem much harder.
Not sure why practically any errors in react-native causes the `_resetListener` to be undefined, but in the mean time, this solution stops the problem.

Update TabViewPagerAndroid with safety check on _resetListener

---

example/src/NoAnimationExample.js
src/TabViewPagerAndroid.web.js

react-native-web aliases `import ... from 'react-native'` into `import ... from 'react-native-web'`.
But it does not implement undocumented or iOS/Android-only components, not even stubs for it.
So I added a stub in this package, which provides a component which just says: not implemented.

When used with react-native-web, do not expect ViewPagerAndroid to be supported

---

src/TabBar.js

When running the TabBar on react-native-web, I got a warning that the Native Animation was not available. This implements the check, and prevents the warning.

Check if NativeAnimatedModules is available before defaulting to useNativeDriver in TabBar

---

example/src/CoverflowExample.js
src/TabViewPagerPan.js

Index from `props` might be out of sync due to async nature of `setState`.
Fixes #448 
Manual testing due to specific nature of the problem.

Use internal current index in TabViewPagerPan instead of the one from props

---

src/SceneMap.js
src/TabViewAnimated.js
src/TabViewPropTypes.js
src/TabViewTypeDefinitions.js

Fix #467 
Change `example/src/NoAnimationExample.js` line 99:
```diff
return (
<TouchableWithoutFeedback
key={route.key}
-            onPress={() => props.jumpTo(route.key)}
+            onPress={() => props.jumpToIndex(index)}
>
<Animated.View style={styles.tab}>
{this._renderIcon(props)({ route, index })}
```

Add deprecation warning to jumpToIndex

---

src/TabViewPagerPan.js

When use Tabbar in RTL apps, first tab shown perfect and as expected but other tabs are blank and doesn't show anything.
After digging in library I found that this issue is related to transformation of View inside `TabViewPagerPan.is`  and it could solve just by inverting translate value for RTL layouts
- Just add tabbar with two or three tabs and use `I18nManager.forceRTL(true)` to change layout direction

RTL support for TabViewPagerPan

---

src/TypeDefinitions.js

After migration to new version, I found missing import in `TypeDefinitions.js` :

fix: missing react import

---

README.md
src/TabBar.js

This PR enables a `onTabLongPress` handler.
If merged, I will also send PRs to `react-navigation-tabs` and `react-navigation`.
Please see my `react-navigation` RFC to understand my motivation: https://github.com/react-navigation/rfcs/pull/55

Add onTabLongPress handler

---

src/PagerExperimental.js

If `PagerExperimental` is used on Android with 1 route and with `useNativeDriver` flag, then it doesn't render anything. Turned out that's because with 1 route `maxTranslate` calculates to `0`, and interpolation becomes
```
Animated.add(panX, offsetX).interpolate({
inputRange: [-0, 0],
outputRange: [-0, 0],
extrapolate: 'clamp',
});
```
which doesn't work well with `useNativeDriver` (strangely enough, if one disables `useNativeDriver`, it works as expected).
Because in case with 1 route this calculates to non-changing animated `0` anyway, I've made this fix.
Use `PagerExperimental` on Android with 1 route and `useNativeDriver`. See that it renders content with my fix and doesn't render without it.

[Android] Fix usage of PagerExperimental with 1 route and with useNativeDriver

---

src/PagerPan.js

`PagerPan` doesn't trigger `props.onIndexChange` when `animationEnabled={false}`. without `Animated.parallel` and it's finished callback, `PagerPan` doesn't call `props.jumpTo` to make it all right.
Use `PagerPan` and set `animationEnabled={false}`, should trigger `props.onIndexChange` correctly.

fix: PagerPan not trigger onIndexChange when disable animation

---

src/TabView.js

There was a flow error. This fixes it.
```
Error ---------------------------------------------------- ../../node_modules/react-native-tab-view/src/TabView.js:121:8
Property `delayRenderOfNonFocusedTabs` is missing in `State` [1].
../../node_modules/react-native-tab-view/src/TabView.js:121:8
121|       !this.state.delayRenderOfNonFocusedTabs ||
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
References:
../../node_modules/react-native-tab-view/src/TabView.js:41:70
41| export default class TabView<T: *> extends React.Component<Props<T>, State> {
^^^^^ [1]
```
cc @Niryo 
Flow passes

Remove unused code which causes a flow error

---

src/TabView.js

The indicator is rendered in the wrong position when the height of the tab view changes.  To fix the calculation, the panX value needs to be set whenever setting the offsetX value.
1. Using `createMaterialTopTabNavigator`, create a navigator with a `tabBarComponent` that changes height when switching tabs.  See example below that has a banner on two tabs but not the last tab.
2. Swipe to tab with different height.
3. Swipe back to previous tab.
Expected Results: indicator is rendered under the active tab.
Actual Results: indicator is rendered under non-active tab.

panX and offsetX need to be set together

---

src/TabBar.js

Utilizing the new accessibility properties provided in react-native 0.57.0. It did not seem to work using the currently deprecated properties on my test devices.
Steps to test:
1. Enable VoiceOver (iOS) or TalkBack (Android)
2. Select a tab
3. It should read something like `Selected. TabName. Tab. x of y. Button`. Previously, it would read `TabName. Tab. x of y.`
It seems like there was an effort to manually assign the role of `Tab` through the `accessibilityLabel` prop. However, that is not in the list of available accessibility roles. Personally, I think it's helpful to have both `Tab` and `Button` announced, but I can remove/change it as needed.

Adding accessibility role and state

---

README.md
src/Pager.js
src/TabView.js

In one of my projects, setting `removeClippedSubviews` to true on Android caused some performance issue.
This PR gives control of this behavior to lib consumer.
Green CI

Control removing clipped subviews via prop

---

src/Pager.js

Change pager.js swipe controll for rtl support
Enable swipping for rtl language

Add rtl support for swipe

---

README.md
src/Pager.js
src/TabView.js
src/types.js

Sometimes I suppose a user might want to define own behavior of timing of spring and I want to make it possible with this PR
Add some config (e.g. `extraSpringConfig`) to `Pager`.

feat: export extra animation options for Pager

---

src/PagerScroll.js

Fix an issue where the initial tab is ignored on iOS and React Native 0.59.x when the initial tab is not the first tab in the set.
This uses the newly introduced [scrollToOverflowEnabled prop](https://github.com/facebook/react-native/commit/e3ac329).
It seems counterintuitive to have this along with `overScrollMode="never"` but `overScrollMode` really controls the ability to scroll past the ends of a `ScrollView`, while `scrollToOverflowEnabled` allows us to manually `scrollTo()` an arbitrary position out of bounds of the `ScrollView`.
I'm unsure of the underlying change in RN0.59.x that caused this, but it seems that the ScrollView hasn't completed layout when the `_setInitialPage()` is called, so it's unable to scroll to a non-zero x value.
Should address …

fix: setting initial tab behaviour for iOS RN 0.59.x

---

example/src/TopBarIconExample.js
example/src/TopBarTextExample.js
src/PagerScroll.js
src/PropTypes.js
src/TabBar.js
src/TypeDefinitions.js

Currently the Pager bounce is disabled and it looks like an Android Pager not iOS scrollview.
Support horizontal bounces for `PagerScoll` to make it looks like an iOS component.
`bouncesEnabled` props is default `false` to avoid affecting existing users.
This PR is for v1.0 because most developers are still using this version.
I will create another PR for v2.0 as soon as possible.

Support horizontal bounces for PagerScoll to make it looks like iOS component

---

src/Pager.js
src/SceneView.js
src/TabBar.js
src/TabBarIndicator.js
src/TabView.js
src/types.js

This drops the undocumented position listener which can cause perf issues by overloading the bridge in favor of a enter listener which can be used for lazy loading

refactor: drop position listeners in favor of enter listeners

---

src/Pager.js
src/SceneView.js
src/TabBar.js
src/TabBarIndicator.js
src/TabView.js
src/types.js

This commit aims to throttle the events from reanimated to avoid overloading JS thread. It changes a few things:
- Due to the throttling, we cannot get the same scroll as you swipe effect on scrollable tab bar, which is probably better as this didn't work smoothly on lower end devices
- We now call onIndexChange as soon as you lift your finger rather than waiting for the animation to finish, which seems to work okay
- Due to throttling, empty page for lazy loaded tabs is more pronounced, but this can be work around by providing a placeholder component
Closes #700, #716

fix: try to improve the performance

---

src/Pager.js
src/TabBar.js
src/TabBarIndicator.js
src/TabBarItem.js
src/memoize.js

Currently the animated nodes used for styles are re-created in render, which means that reanimated does a lot of expensive work detaching and reattaching them. Due to this, the framerate of the JS thread goes down to 0 FPS even on high-end devices when switching tabs quickly.
This PR implements memoization for the animated nodes so they are only recreated when necessary. On low-end devices, this keeps the JS frame rate around 12+ FPS on low-end devices and 40+ on high-end devices.
Related to #720

fix: memoize animated nodes to improve performance

---

README.md
src/Pager.tsx
src/TabView.tsx

In cases when `TabView` is used along with another handlers of `react-native-gesture-handler`, it's required to pass additional props to underlying `PanGestureHandler`, such as various refs to wait for/simultaneously work with etc. Different people need to pass different props, so I decided to accept and spread just an object of props instead of listing each of "allowed" additional props. There's no Flow typedefs in `react-native-gesture-handler`, so the type of `pagerProps` is just `Object`.
Closes #486.
Small change. I tested it personally by passing `pagerProps={{ maxPointers: 1 }}` and ensuring that I wasn't able to swipe with two fingers.

Allow passing additional props to pager

---

README.md
src/Pager.tsx
src/TabView.tsx
src/types.tsx

Previously evaluating next index was based only on position OR velocity. It wasn't considering BOTH of them which appears to natural behavior.
I believe that the expected scenario is that we can calculate is component left without snapping will rather stop decaying on the current or next/previous page. 
I figured out (calculation attached) that final position (actually delta of current and final extrapolated) is ~ to `v^2` and knowing that I implemented a more physical-based model for evaluating next index. 
I changed the implementation of calculating the next index. Also, I had to drop `swipeVelocityThreshold` and `swipeDistanceThreshold` and then I replaced it with `swipeVelocityImpact`. I think it's a good time for this move bc it's not very breaking and this version is not yet by …

feat: consider both velocity and position while calculating index

---

package.json
src/Pager.tsx

previously, when gesture wasn't active, we checked if the gesture exceeded the minimum threshold (this was due to activeOffsetX not being respected on Android),
- if yes, we calculate the next position based on gesture distance or velocity
- if no, we transition to what the value of index was
this addressed 2 cases: the first condition would trigger when a gesture was performed, the second one will trigger if the index changed due to other means such as state update.
this check was mistakenly removed in e7f832c
the new code checked for `State.END`, which resulted in the tab switch due to state update not working at times. this is because the `gestureState` value is different when a gesture was cancelled, e.g. due to a vertical gesture or focus on an input element.
closes #806, closes #809

fix: don't consider velocity and gesture distance if gesture didn't end

---

README.md
src/Pager.tsx
src/TabView.tsx
src/types.tsx

Currently the keyboard is dismissed only when a swipe gesture starts. This commit changes the behaviour so that:
- Keyboard is dismissed if the tab index changes
- When a gesture begines, keyboard is dismissed, but if the index didn't change at end of the gesture, it's restored
This is closer to iOS native behaviour and is based on previous work by [@skevy](https://github.com/skevy) in react-navgation:
https://github.com/react-navigation/react-navigation/pull/3951
The old behaviour is left as the 'on-drag' option for backward compatibility.

feat: improve keyboard handling during tab change

---

README.md
src/Pager.tsx

It appears that previous logic was considering velocity in a too aggressive way. So I'd like to get rid of extra velocity multiplication. It should lead to more natural behavior. 
If it works, I'd like to move these changes to stack-view as well.

Change logic of switching tabs

---

README.md
example/src/App.tsx
example/src/AutoWidthTabBarExample.tsx
example/src/CustomIndicatorExample.tsx
src/TabBar.tsx
src/TabBarIndicator.tsx
src/TabBarItem.tsx

The PR is based on #751 and #823 (thanks to @Taylor123 and @ankeetmaini)
The improvements include:
1. For tab bar with `width: 'auto'`, fade in the indicator when we have the layout. This avoids sometimes noticeable jump in the indicator.
1. Memoize the `getTabWidth` prop passed to `renderIndicator`. This makes sure that the animated nodes are memoized properly as well and fixes the issue with the width jumping at end of animation on Android.
1. Make sure we adjust the scroll value only after the layout is available. This fixes an issue where sometimes the scroll position is incorrect on initial load.
1. Fixed calculation of center distance so the correct tab is centered.
1. Minor tweak to how we store tab widths in state, use an object with route key as keys which should be more accurate …

 feat: support `width: 'auto'` in tabStyle

---

README.md
src/Pager.tsx
src/TabView.tsx
src/types.tsx

In this PR I add springVelocityScale parameter as a config of Pager. Toss defines how much velocity of gesture impacts on an initial velocity of Pager. Found it very useful in bottom sheet. 
Also, @christianbaroni asked me for doing it so here you are, Christian 😄 
However, while writing this code I figured out interesting bug in Pager which led to fact that initial velocity of spring was always zero. It happened bc previously velocity was set only if clock was not running. However few lines above we made similar check and if clock was not running... then we were starting it, so as the result there was no chance that in current state clock was not running. 
I fixed it by moving starting clock few lines below.
You may add `springVelocityScale ={4}` param to `ScrollableTabBarExample`

feat: add springVelocityScale effect

---

README.md

The given example at [Quick Start](https://github.com/react-native-community/react-native-tab-view#quick-start) does not work because it's missing navigationState index.
A broken example is confusing for beginners.

docs: update Quick Start example with 0 index state

---

src/index.tsx

Currently it’s possible to import `TabBar` and use the component as the tab bar in `renderTabBar`
```
import { TabBar } from 'react-native-tab-view';
...
<TabView
renderTabBar={props => <TabBar {...props} />}
...
/>
```
Similarly it should also be possible to import `TabBarIndicator` so it can be used in `renderIndicator`.
```
import { TabBarIndicator } from 'react-native-tab-view';
...
<TabBar
renderIndicator ={props => <TabBarIndicator {...props} />}
...
/>
```
I was attempting to modify the styles of the default indicator and realized that I couldn't import the component like this.
For testing, ensure that the import statement doesn't introduce any errors.

feat: export TabBarIndicator

---

src/ScrollPager.tsx

cc @osdnk @satya164 
I opened #993 after observing that `onIndexChange` does not appear to work when passing `renderPager={props => ScrollPager {...props } />`. This component only calls `onIndexChange` when it's `jumpTo` API method is called, but not simply as a result of scrolling within the inner `ScrollView`.
I have no idea but it doesn't look like there are any existing tests so I imagine this isn't a blocker. I would love to know how to test `ScrollView` interactions though so if anyone has insight please share.

fix: teach ScrollPager how to call onIndexChange

---

src/index.tsx
tsconfig.json

fixed babel typescript transpile error for Props type exports (#969, #945):
```
./node_modules/react-native-tab-view/lib/module/index.js
"export 'Props' (reexported as 'TabBarProps') was not found in './TabBar'
```
This is mainly caused by a well-known babel typescript transform limit that it can not tell types from values, see babel/babel#8361
Change summary
- added `isolatedModules:true` in tsconfig.json so typescript will prevent such problem going forward
- refactor the `index.ts` to explicitly export Props as types.
the `example` now worked

fix: type export warning in webpack

---

src/TabBar.tsx

On windows there are useless scrollbar around TabBar (react-native-web). I don't know what is the purpose of `overflow:scroll` here but changing to `overflow:hidden` fixes the issue. on mac it is reproducible if you set _show scroll bars_ to _Always_ in _Settings -> General_ Which this is the default behaviour on windows
1. Create a simple tab view
2. You should see the scrollbars

fix: fix scrollbars being always visible in TabBar on web

---

src/ScrollPager.tsx

Probably fixes https://github.com/react-native-community/react-native-tab-view/issues/1011 and is def an expected behavior or at least better than current

fix: call onIndexChange only if scrollview was dragged

---

src/Pager.tsx
src/index.tsx

This allows child PanGestureHandlers to call addGestureHandlerRef using PagerConsumer (and PagerContext), and additionally allows them to waitFor the Pager PanGestureHandler through the addition of gestureHandlerRef to Pager.providerVal
Using a PanGestureHandler inside a MaterialTopTabNavigator from react-navigation steals pan gesture input from the Pager used by TabView. 
Inside a MaterialTopTapNavigator with `swipeEnabled = true`
```tsx
import React, { Component } from 'react';
import { PanGestureHandler } from 'react-native-gesture-handler';
import Animated from 'react-native-reanimated';
import { PagerConsumer, PagerContextType } from 'react-native-tab-view';
class Example extends Component {
private pager: PagerContextType | undefined;
private panGestureHandlerRef = …
```

fix: exported Pager, PagerConsumer, PagerContext, and PagerContextType

---

src/TabBar.tsx

Solves issue: https://github.com/react-native-community/react-native-tab-view/issues/1033
Animation frames are fired off but never cancelled if the component unmounts.
The issue is difficult to reproduce, it can occur when the view is in an animated component.

fix: clean up animation frames

---

src/TabBarIndicator.tsx

Following the implementation https://github.com/satya164/react-native-tab-view/blob/master/src/TabBarIndicator.tsx#L123
width can be a string or a number.

fix: fix `TabBarIndicator` width props type

---

src/Pager.tsx

This component always logs error in the console when testing.
```
Warning: Can't call setState on a component that is not yet mounted. This is a no-op, but it might indicate a bug in your application. Instead, assign to `this.state` directly or define a `state = {};` class property with the desired state in the Pager component.
Warning: Can't call forceUpdate on a component that is not yet mounted. This is a no-op, but it might indicate a bug in your application. Instead, assign to `this.state` directly or define a `state = {};` class property with the desired state in the Pager component.
```
PR adds some mounted checks.
As long as tests pass and dont log.

fix: Only update state if mounted.

---

src/TabBarItem.tsx

For tabbar labels I want to add styles and either active or inactive color.  The assumption is that the color prop would override the style prop.

fix: moved color to last prop

---

src/SceneView.tsx

This PR fixes https://github.com/satya164/react-native-tab-view/issues/1103.
Basically, just clear timeout on component unmount.

fix: clearTimout on unmount (#1103)

---

src/Pager.tsx

There's a minor bug in web version of tabview. `currentIndexRef` in Pager.tsx file is only updated when tabs are switched using gesture. When they are switched using tab bar, you can not navigate back to tab which was mounted first.
Steps to reproduce:
Create a tabview with 3 tabs. Let say initial navigationState is { index: 0, title: 'abc' }. 
Now switch to any of the other 2 tabs
Now try to switch to 1st tab . It won't switch
Please note that gesture is not being used. `navigationState` is being updated and passed to TabView. In case of gesture it works correctly.

[web]: updating currentIndexRef when tab is switched by clicking tab bar

---

README.md

Add React Native compatibility disclaimer to readme
App crash using version 3.x.x of this library as in this issue https://github.com/satya164/react-native-tab-view/issues/1143
no need.

feat: add rn compatibility disclaimer table to readme.md

---

src/TabBar.tsx

- Replicated in iOS. When I try scrolling on the tabBar there will be a vertical indicator show on the right side of it.
- This issue happened when I custom the TabBarItem.

fix Vertical Scrollbar show on Tabbar

---

src/PanResponderAdapter.tsx

**Motivation**
According to this comment https://github.com/satya164/react-native-tab-view/issues/1306#issuecomment-1058763296 This PR just changes the place of onIndexChange method.

fix: move onIndexChange

---

README.md
example/src/App.tsx
example/src/TabBarGapExample.tsx
src/TabBar.tsx
src/TabBarIndicator.tsx

The goal is to support spacing between tabs ( see #1020 ) - It is roughly doable with some customizations (thanks to `renderTabBarItem` and `renderIndicator` methods) but it requires to modify internal methods (`getTranslateX` for example)  
I have added one example ( `TabBarSpacingExample` )

feat: add tabBarSpacing property

---

README.md
src/TabView.tsx

Pager component already has a style prop, this just exposes it to the end user
**Motivation**
I have a use case where part of the custom tab bar needed to overlap part of the scene. The only way to do it would be to add a negative top margin to the Pager view, however the style prop that is exposed on the Pager view is not exposed on the TabView so currently I can't achieve this use case.

Expose the style prop accepted by the Pager component

---

README.md
src/TabBar.tsx

**Motivation**
I was unable to scroll the tab bar and couldn't press on tabs that were not in the visible view as detox requires it to be a scrollable component. Adding a test id fixes it as we can grab the tabBar using `by.id(testID)`.
**Test plan**
I simply added a tabBarTestID prop in TabBar to grab the bar. Now it is scrollable in both Android & iOS

test: `testID` added in `TabBar` for testing

---

example/package.json
example/yarn.lock
package.json
yarn.lock

**Motivation**
At the moment latest version of pager-view is not working correctly with expo managed projects. Commands like setPage are not being called on the native side. 
**Test plan**
CI
**Code formatting**
Look around. Match the style of the rest of the codebase. Run `yarn lint --fix` before committing.

chore: downgrade pager-view to 6.0.2
