satya164/react-native-tab-view

- src/TabViewPanResponder.js
This just needed some parenthesis added.
> Fix condition that determines whether to grant gestures to horizontal swipe

- src/TabBar.js
Reverts react-native-community/react-native-tab-view#5
> Revert "feat: pass position to scene for label animation"

- src/TouchableItem.js
> fix: improve TouchableItem press animation

- src/TabViewPage.js
- src/TabViewPanResponder.js
As discussed in #38, this PR adds the necessary logic to resolve that issue.
> Better handing of a canceled swipe.

- README.md
- src/TabViewTransitioner.js
- src/TabViewTransitionerTypes.js
this allows to stop jumping to a route
> feat: add canJumpToTab prop to TabViewTransitioner

- src/TabViewPanResponder.js
This should fix the bug described in #42.
> Check if startDirection is 0

- src/TabViewTransitioner.js
> Fixes tab transition to jump if update occurs during transition

- src/TabViewTransitioner.js
this fixes jumpToTab being called on the unmounted component
> fix maximum callstack size error in jumpToTab

- src/TabBar.js
> Removed scroll on header in web

- src/TabBar.js
- src/TabViewPagerAndroid.js
> RTL support

- LICENSE.md
It's a standard MIT license. Looks like you forgot add it :)
> Add license.md

- src/TabViewPagerAndroid.js
- Due to the `requestAnimationFrame` logic, we are seeing `TabBarPagerAndroid` be stuck on the incorrect tab intermittently (as high as 50%)
- We see that `navigationState.index` is being passed correctly to `TabBarPagerAndroid`, but `TabBarPagerAndroid` is showing the incorrect tab
- This is because of a race condition between the existing `requestAnimationFrame` callback and the call to `_handlePageChange ` in `componentDidUpdate`.
- When the issue happens, this is the series of events:
1. `componentWillReceiveProps` is called with `nextProps` with `navigationState.index = 0`
2. `requestAnimationFrame` is called with callback to set page to `0` because of new child count
3. `componentDidUpdate` is called with `navigationState.index = 0` and page is set to `0`
4. Navigation state changes …
> fix: prevent android tab view pager from entering inconsistent state

- .flowconfig
- __tests__/TabViewAnimated.test.js
- __tests__/TabViewPagerAndroid.test.js
- __tests__/TabViewPagerScroll.test.js
- example/src/App.js
- example/src/BasicListView.js
- example/src/BottomBarIconTextExample.js
- example/src/CoverflowExample.js
- example/src/NoAnimationExample.js
- example/src/ScrollViewsExample.js
- example/src/TopBarIconExample.js
- example/src/TopBarTextExample.js
- flow-typed/npm/enzyme_v2.3.x.js
- package.json
- src/SceneMap.js
- src/TabBar.js
- src/TabViewAnimated.js
- src/TabViewPagerAndroid.js
- src/TabViewPagerPan.js
- src/TabViewPagerScroll.js
- src/TabViewTypeDefinitions.js
- src/TouchableItem.js
https://github.com/react-native-community/react-native-tab-view/issues/359
There are no more flow or linting errors.
@satya164 Please consider merging this request.
> upgrade to flow 0.53.0 & fix lint errors

- src/TabViewPagerPan.js
Fix onSwipeEnd do not callback
> [FIX] onSwipeEnd do not callback function

- README.md
Super minor change, just removing an unused import from the demo.
> remove unused import from demo

- README.md
- src/TabBar.js
> feat: add `contentContainerStyle` to TabBar

- src/Pager.js
> fix: reset _isSwipeGesture when state.finished (#719)

- src/TouchableItem.js
…nation` description: https://github.com/facebook/react-native/blob/master/Libraries/Components/Touchable/Touchable.js\#L418
Fix issue: https://github.com/react-navigation/react-navigation/issues/2458.
According to `Touchable props rejectResponderTermination` description: https://github.com/facebook/react-native/blob/master/Libraries/Components/Touchable/Touchable.js/#L420
> fix: fix issue with triggering press while scrolling on iOS

- src/Pager.js
This is configuration used by stack navigator. Feels very similar to what reddit app has.
> fix: tweak spring config for animation

- src/TabBar.tsx
This allows us to add custom margin or width to the tab bar without needing to override the layout prop.
> fix: measure tab bar layout instead of using tabview layout

- src/Pager.tsx
I made a mistake and didn't set value properly while committing, sorry.
> Update default velocity impact value

- .circleci/config.yml
- example/src/CustomIndicatorExample.tsx
- src/TabBar.tsx
closes #184, closes #742
the gif is from iOS, but I have tested on both iOS and Android and it works.
> fix: fix scrollable tab bar in RTL

- README.md
No information about it, spent about 1 hour.
> docs: add info about integration with react-native-navigation on android

- src/TabBar.tsx
Add the ability to customize the indicatorContainer so that we can achieve that kind of style.
> Add indicatorContainerStyle

- .github/ISSUE_TEMPLATE/bug_report.md
Added syntax highlighting URL, so it's easy to read code
Not able to read code easily in issues
N/A
> Add syntax highlighting url for issue template

- src/TabBar.tsx
closes #877
Read comment in code
> fix: move layout from state to class member

- example/src/NativePagerExample.tsx
- src/TabView.tsx
- src/index.tsx
> feat: add example

- README.md
- src/Pager.tsx
- src/TabView.tsx
Now it's possible to replace backend (pager) with another component if needed
Does not affect existing code
> feat: expose render pager prop

- README.md
Follow up with PR adding `ScrollPager`
no code changes
> docs: add docs for ScrollPager

- package.json
- src/ScrollPager.tsx
- yarn.lock
I've updated `@types/react-native` to fill in the missing props for ScrollView https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41862
This can remove the TODO comment for adding missing props.
yarn typescript
> chore: update @types/react-native and remove TODO

- src/TabBarItem.tsx
Updated accessibility properties on `TouchableItem` to match the latest RN https://reactnative.dev/docs/accessibility#accessibility-properties
Test on device with enabled VO/TalkBack.
> fix: update accessibility props for latest RN

- README.md
> docs: fix the link to gesture handler

- README.md
react-native-pager-view text and link are misspelled.
> chore: fix broken link in README

- src/Pager.tsx
The gesture handling on the web is broken for RTL languages. This pull request fixes the responders for RTL support.
`react-native-pager-view` support for RTL languages is not ideal on the web.
- Have at least two tabs.
- Use the web version with RTL locale.
- The gesture handling is working correctly.
> fix: RTL support for the web

- src/PanResponderAdapter.tsx
Reverts satya164/react-native-tab-view#1384
> Revert "fix: move onIndexChange"

- src/TabBar.tsx
**Motivation**
Make the TabBar use FlatList instead of ScrollView
**Test plan**
CI / Review
> feat: add flatList to TabBar

- example/src/Shared/Albums.tsx
- example/src/Shared/Article.tsx
- example/src/Shared/Chat.tsx
- example/src/Shared/Contacts.tsx
- example/src/Shared/Profile.tsx
**Motivation**
This pull request introduces functional components for shared components in example app.
> feat: add functional components to example

- example/package.json
- example/yarn.lock
- package.json
- src/PagerViewAdapter.tsx
- src/PanResponderAdapter.tsx
- src/SceneMap.tsx
- src/SceneView.tsx
- src/TabBar.tsx
- src/TabBarIndicator.tsx
- src/TabBarItem.tsx
- yarn.lock
This pull request introduces function based components. The goal is to make this library easier to maintain and easier to contribute to.
> refactor: change components to function based
